    [package]
    name = "ores-otel-sidecar"
    version = "0.1.0"
    edition = "2021"
    license = "MIT"
    description = "Sidecar for ores-otel"
    repository = "https://github.com/ores-otel/ores-otel-sidecar.rs"

    [[bin]]
    name = "ores-otel-sidecar"
    path = "src/main.rs"

    [dependencies]
    serde = { version = "1", features = ["derive"] }
    serde_json = "1"
    thiserror = "2"

[lints.rust]
unsafe_code = "forbid"


